# Generated by Django 3.2.3 on 2022-10-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(default='', max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default='100.0', max_digits=15)),
            ],
        ),
    ]
