# Generated by Django 3.2.3 on 2022-10-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Name', max_length=50),
            preserve_default=False,
        ),
    ]
