# Generated by Django 3.2.3 on 2022-10-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
