# Generated by Django 3.2.3 on 2022-10-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
