# Generated by Django 3.2.3 on 2022-10-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20221023_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='transactions',
            field=models.JSONField(default=None),
        ),
    ]
