# Generated by Django 3.2.3 on 2022-10-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_customer_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='transactions',
        ),
    ]
